### ISSUE TITLE
Encoding issue causes exception in replay

### ISSUE THREAD

**Issue by davepeck** [davepeck/httreplay#12]
This appears to be related to the @agriffis pull request that I merged a little while ago, but a simple repro:

    import requests
    import httreplay
    httreplay.start_replay("/tmp/foo")
    requests.get("http://nytimes.com/")  # Just some HTTP thing

**Comment by agriffis** [comment]
Hi Dave. I can't look closely right now, but I think this will do the trick:

```
diff --git a/httreplay/stubs/base.py b/httreplay/stubs/base.py
index 3dd8e35..c510be1 100644
--- a/httreplay/stubs/base.py
+++ b/httreplay/stubs/base.py
@@ -268,8 +268,7 @@ class ReplayHTTPResponse(object):
 
             try:
                 # Store body directly as text if it will decode properly.
-                body.decode('utf8')
-                replay_response['body_text'] = body
+                replay_response['body_text'] = body.decode('utf8')
             except UnicodeDecodeError:
                 # Store body as quoted printable.
                 # Remove unneccessary =\n pairs which make searching hard.
```

This should guarantee that body_text is a unicode object later, regardless of whether it came from `make_replay_response()` or JSON decoding.

**Comment by davepeck** [comment]
Thanks and, yes, I found that too.

I happened to spend a moment looking at `vcr.py` today and, frankly, I think it's a much better option at this point. I'm considering calling it quits with `httreplay` entirely as `vcr.py` is more feature rich, has a larger community, and has done some better thinking about how to manage patches, etc. at this point.

Any strong feelings about this?

**Comment by agriffis** [comment]
I'll probably switch to `vcr.py` too, but not immediately since I have a pretty large project organized around `httreplay` at the moment.  I'd prefer if you don't yank `httreplay` from PyPI for example, even if you'd like to hang a banner in the README declaring it unmaintained.

**Comment by davepeck** [comment]
Yeah, no plans to yank it from `PyPi` but I do think EOLing it is the right way to go. As a for instance, a minor change in Python's `httplib` from `2.7.8` to `2.7.9` has highlighted even more basic deficiencies in `httreplay`. So it goes, so it goes.

**Comment by kevin1024** [comment]
> a minor change in Python's httplib from 2.7.8 to 2.7.9 has highlighted even more basic deficiencies in httreplay

Ugh tell me about it.  Maintaining a library based around a monkeypatch isn't easy :)

If there's anything I can do to ease the transition, feel free to open issues on vcr.py.

**Comment by davepeck** [comment]
@kevin1024 Thanks -- and, yeah, I imagined you had to deal with that little surprise. Overall the transition between the two is pretty straightforward, unless you happen to have more complex filtering/matching, in which case it's a small delta I think.

I suppose it _would_ be nice if the `vcr.py` docs had a few lines that mentioned how to use it _without_ a context manager.

**Comment by kevin1024** [comment]
Yup, here's our fix: https://github.com/kevin1024/vcrpy/issues/130

I'll happily take a pull request to improve the documentation.  It can also be used as a decorator.  Or was there a different method you had in mind?

**Comment by davepeck** [comment]
No decorator either -- just `start()` and `stop()` methods would be nice.

**Comment by lukas-gitl** [comment]
Yep, that's exactly what I'd want as well!

**Comment by davepeck** [comment]
This bug is fixed with 73a7a48 -- I'll close it and we can move conversation re: vcr/httplib etc elsewhere. :-)

**Comment by agriffis** [comment]
Ouch, I'm pretty sure that fix is going to break something for me. The comment there explains that it should be bytes rather than unicode. You didn't like the fix I proposed earlier?

**Comment by davepeck** [comment]
Ugh, looks like I screwed up. One sec.

**Comment by davepeck** [comment]
Sorry about that -- correct fix up.

**Comment by IvanMalison** [comment]
@lukas-gitl @davepeck 

Do you guys still definitely want `start` and `stop` methods -- I'd be happy to add them, but I've always sort of thought it was a good thing that vcrpy forces you to use a contextmanager/decorator because this gives you programming language level guarantees that things WILL be unpatched after the relevant code has exectued that is robust to exceptions etc.

What is the use case for `start` and `stop` that isn't covered by a context manager?

**Comment by agriffis** [comment]
@IvanMalison `start` and `stop` would be useful for calling from `unittest.TestCase.setUp` and `tearDown`.

**Comment by davepeck** [comment]
@IvanMalison What @agriffis said. :-)
